fix:[ TypeError: actualEvent.categories.sort is not a function ] expect : [ should return 200 with basic data for all the events (order doesn't matter) when no query params given ] on: get/events endpoint