fixed: ================= { Test DELETE /users/:id/image endpoint : should return 404 when trying to delete the profile photo for a user that doesn't exist } {  GET /events/:id/attendee endpoint
AssertionError: expected header 'content-type' to have value image/jpeg but got 'image/undefined'
}